// AUTOGENERATED: DO NOT EDIT
using System;

namespace Synergy88
{
	[Serializable]
	[Flags]
	public enum EButtonType
	{
		Invalid,
		Login,
		LoginFacebook,
		MoreGames,
		Currency,
		Help,
		Leaderboard,
		Shop,
		Play,
		Settings,
		Back,
		Score,
		Refresh,
		Home,
		Upload,
		Ads,
		Credits,
		Restore,
		MoreGamesItem,
		ShopItem,
		CoinItem,
		Popup001,
		Popup002,
		Popup003,
		Close,
	}
}
