// AUTOGENERATED: DO NOT EDIT
using System;

namespace Synergy88
{
	[Serializable]
	[Flags]
	public enum EScene
	{
		Invalid,
		System,
		Services,
		Audio,
		Splash,
		Preloader,
		Login,
		Home,
		Coins,
		Shop,
		Settings,
		Game,
		Results,
		PopupCollection,
		Back,
		Currency,
		Background,
		MoreGames,
		Cleaner,
		Max,
	}
}
